In [1]:
from tensorflow.keras.preprocessing.text import one_hot

sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [2]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [3]:
## define the vocab size
voc_size = 10000

# One hot representation 
one_hot_representation = [one_hot(words, voc_size) for words in sent]
one_hot_representation

[[1186, 1476, 7439, 498],
 [1186, 1476, 7439, 4654],
 [1186, 1474, 7439, 3388],
 [1154, 306, 493, 9361, 272],
 [1154, 306, 493, 9361, 2741],
 [3926, 1186, 6206, 7439, 7143],
 [9287, 946, 1854, 9361]]

In [4]:
## word embedding representation 
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
 

In [5]:
import numpy as np 
sent_length = 8
Embedded_docs = pad_sequences(one_hot_representation, padding = 'pre', maxlen = sent_length)
print(Embedded_docs)

[[   0    0    0    0 1186 1476 7439  498]
 [   0    0    0    0 1186 1476 7439 4654]
 [   0    0    0    0 1186 1474 7439 3388]
 [   0    0    0 1154  306  493 9361  272]
 [   0    0    0 1154  306  493 9361 2741]
 [   0    0    0 3926 1186 6206 7439 7143]
 [   0    0    0    0 9287  946 1854 9361]]


In [7]:
## Feature representaion 
dim = 10
model = Sequential()
model.add(Embedding(voc_size, dim, input_length = sent_length))

In [9]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [10]:
model.predict(Embedded_docs)

1/1 [==============================] - 1s 618ms/step


array([[[ 0.0017476 ,  0.04828705, -0.02913619,  0.02017263,
          0.01695944,  0.04504922,  0.04617374, -0.02933647,
          0.04090503, -0.03417585],
        [ 0.0017476 ,  0.04828705, -0.02913619,  0.02017263,
          0.01695944,  0.04504922,  0.04617374, -0.02933647,
          0.04090503, -0.03417585],
        [ 0.0017476 ,  0.04828705, -0.02913619,  0.02017263,
          0.01695944,  0.04504922,  0.04617374, -0.02933647,
          0.04090503, -0.03417585],
        [ 0.0017476 ,  0.04828705, -0.02913619,  0.02017263,
          0.01695944,  0.04504922,  0.04617374, -0.02933647,
          0.04090503, -0.03417585],
        [-0.00280664, -0.03900357,  0.0108736 , -0.01050453,
          0.02467278,  0.00869057, -0.01848965, -0.0363255 ,
          0.02340556, -0.00029843],
        [-0.04818876, -0.03743387, -0.04417298,  0.02821526,
         -0.00141943,  0.01591827, -0.01598326, -0.03548576,
         -0.01873197,  0.00647746],
        [-0.03023499,  0.0214725 , -0.02776641,  0.0